export var codeTags = [
   {
      tag: 'var',
      path: 'Statements/var',
      weight: 1,
   },
   {
      tag: 'if',
      path: 'Statements/if...else',
      weight: 2,
   },
   {
      tag: 'else',
      path: 'Statements/if...else',
      weight: 2,
   },
   { tag: '%', path: 'Operators/remainder', weight: 1 },
   { tag: ' + ', path: 'Operators/Addition', weight: 1 },
   { tag: ' - ', path: 'Operators/Subtraction', weight: 1 },
   { tag: ' * ', path: 'Operators/Multiplication', weight: 2 },
   { tag: ' / ', path: 'Operators/Division', weight: 2 },
   { tag: '{', path: 'Statements/block', weight: 1 },
   { tag: ' = ', path: 'Operators/Assignment', weight: 1 },
   { tag: ' == ', path: 'Operators/Equality', weight: 1 },
   { tag: ' === ', path: 'Operators/Strict_equality', weight: 1 },
   { tag: ' > ', path: 'Operators/Greater_than', weight: 1 },
   { tag: ' < ', path: 'Operators/Less_than', weight: 1 },
   { tag: ' != ', path: 'Operators/Inequality', weight: 1 },
   { tag: ' >= ', path: 'Operators/Greater_than_or_equal', weight: 1 },
   { tag: ' <= ', path: 'Operators/Less_than_or_equal', weight: 1 },
   { tag: '(', path: 'Operators/Grouping', weight: 1 },
   { tag: '//', path: 'Lexical_grammar#comments', weight: 1 },
];
